services:
  app:
    container_name: dem-app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      MARIADB_HOST: dem-mariadb
      MARIADB_PORT: 3306
      MARIADB_DATABASE: test
      MARIADB_USER: root
      MARIADB_PASS: rootpass
      MARIADB_CONN: 10
  mariadb:
    container_name: dem-mariadb
    image: mariadb:10.9
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: test
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
  redis:
    container_name: dem-redis
    image: redis:alpine
    ports:
      - "6379:6379"
